In [0]:
import tensorflow as tf

In [2]:
place1= tf.placeholder(tf.int16)
place2=tf.placeholder(tf.int16)
# place3=tf.placeholder(tf.int16)

add=tf.add(place1,place2)

with tf.Session() as sess:
  a=sess.run(add,feed_dict={place1: 3, place2:5} )
  print(a)

8


Basic Operations example using TensorFlow library.

In [3]:
#define two constant tensors, this tensor is a 2*2 matrix 
a = tf.zeros((2,2)); 
b = tf.ones((2,2))
a.get_shape()
print(a)
b.get_shape()
#b.eval()
with tf.Session() as sess:
  print(b.eval())
  print(a.eval())

Tensor("zeros:0", shape=(2, 2), dtype=float32)
[[1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]]


In [4]:
#define two constant tensor, this tensor is a 1-d variables 
tfa = tf.constant(5.0)
tfb = tf.constant(6.0)
c = tfa * tfb
print(c)

with tf.Session() as sess:
    print(sess.run(c))
    print(c.eval())
    print("?")

# The value returned by the constructor represents the output
# of the Constant op.
a1 = tf.constant(2)
b1 = tf.constant(3)
c1 = tf.constant(4)


# Launch the default graph.
with tf.Session() as sess:
    print "a1: %i" % sess.run(a1), "b1: %i" % sess.run(b1)
    print "Addition with constants: %i" % sess.run(a1+b1+c1)
    print "Multiplication with constants: %i" % sess.run(a1*b1+c1)


Tensor("mul:0", shape=(), dtype=float32)
30.0
30.0
?
a1: 2 b1: 3
Addition with constants: 9
Multiplication with constants: 10


In [5]:
# Basic Operations with variable as graph input
# The value returned by the constructor represents the output
# of the Variable op. (define as input when running session)
# tf Graph input
a2 = tf.placeholder(tf.int16)#variable
b2 = tf.placeholder(tf.int16)
a3=tf.placeholder(tf.int16)
a4=tf.placeholder(tf.int64)



# how to use feed_dict to initialize tensor 
add = tf.add(a3, b2)
mul = tf.multiply(a2, b2)
with tf.Session() as sess:
    # Run every operation with variable input
    print (sess.run(add,feed_dict={a3: 4, b2:6}))
    print "Addition with variables: %i" % sess.run(add, feed_dict={a3: 4, b2: 5})
    print "Multiplication with variables: %i" % sess.run(mul, feed_dict={a2: 6, b2: 7})
    
    
 

10
Addition with variables: 9
Multiplication with variables: 42


In [6]:
w1 = tf.ones((2,2))
# new ! now we use the tensor variables 
w2 = tf.Variable(tf.zeros((2,2)), name = "weights")
with tf.Session() as sess:
    print(sess.run(w1))
    sess.run(tf.global_variables_initializer())#
    print(sess.run(w2))

Instructions for updating:
Colocations handled automatically by placer.
[[1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]]


In [7]:
#updateing the variable state
state = tf.Variable(0, name="counter")
for i in range(3):
  state = tf.add(state, tf.constant(1))
  with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(state))
# update = tf.assign(state, new_value)



    

1
2
3


In [8]:
#run multiple operation 
input1 = tf.constant(3.0)
input2 = tf.constant(2.0)
input3 = tf.constant(5.0)
intermed = tf.add(input2, input3)
mul = tf.multiply(input1, intermed)
with tf.Session() as sess:
  result = sess.run([mul, intermed])
  print(result)

[21.0, 7.0]


In [9]:
input1 = tf.placeholder(tf.float16)
input2 = tf.placeholder(tf.float16)
output = tf.add(input1, input2)
with tf.Session() as sess:
  print(sess.run([output], feed_dict={input1:[7.], input2:[2.]}))

[array([9.], dtype=float16)]


In [0]:
# ----------------
# More in details:
# Matrix Multiplication from TensorFlow official tutorial

# Create a Constant op that produces a 1x2 matrix.  The op is
# added as a node to the default graph.
#
# The value returned by the constructor represents the output
# of the Constant op.
matrix1 = tf.constant([[3., 3.]])

In [0]:
# Create another Constant that produces a 2x1 matrix.
matrix2 = tf.constant([[2.],[2.]])

In [0]:
# Create a Matmul op that takes 'matrix1' and 'matrix2' as inputs.
# The returned value, 'product', represents the result of the matrix
# multiplication.
product = tf.matmul(matrix1, matrix2)

In [13]:
# To run the matmul op we call the session 'run()' method, passing 'product'
# which represents the output of the matmul op.  This indicates to the call
# that we want to get the output of the matmul op back.
#
# All inputs needed by the op are run automatically by the session.  They
# typically are run in parallel.
#
# The call 'run(product)' thus causes the execution of threes ops in the
# graph: the two constants and matmul.
#
# The output of the op is returned in 'result' as a numpy `ndarray` object.
with tf.Session() as sess:
    result = sess.run(product)
    print result

[[12.]]
